name: book-generate-pdf
run-name: "Generate Book PDF"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  BOOK_SOURCE_DIR: ${{ github.workspace }}/book
  BOOK_BUILD_DIR: ${{ github.workspace }}/build

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    container:
      image: asciidoctor/docker-asciidoctor
      volumes:
        - ${{ github.workspace }}:/documents
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "asciidoctor-pdf"
        run: |
          asciidoctor-pdf \
            -a pdf-themesdir=$BOOK_SOURCE_DIR/themes \
            -a pdf-theme=basic \
            -a pdf-fontsdir=$BOOK_SOURCE_DIR/fonts \
            -D $BOOK_BUILD_DIR \
            $BOOK_SOURCE_DIR/index.adoc
      - name: "Save generated book PDF as build artifact"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: book
          path: build
